### PR TITLE
Generate og:url

### LINKED ISSUE #36: Generate og:url
### Clear and concise description of the problem

Other Open Graph tags, like `og:title`, `og:description`, etc. can and should be added separately from i18n, but given the logic included in this package of turning localized routes into `link`and `meta` tags, it would be great to generate the `og:url` [metadata](https://ogp.me/#metadata) in additional to the already generated `og:locale` ones, so that systems relying on Open Graph (e.g. Facebook scrapers) are satisfied. 

### Suggested solution

In `/src/compatibles/head.ts`, rewrite `addCanonicalLinks` into `addCanonicalLinksAndOgUrl`

### Alternative

- Write a separate `addOgUrl` function, but most of the logic / intermediate steps would be the same as `addCanonicalLinks`
- Add a new config parameter `addOgUrl: boolean` to maximize flexibility: thought it wasn't necessary

### Additional context

image
See https://developers.facebook.com/docs/sharing/webmasters/#basic

### Validations

- [X] Follow our [Code of Conduct](https://github.com/intlify/routing/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/intlify/routing/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by tmlmt**
### Description

Generating `og:url` as canonical url 

### Linked Issues

Closes #36

### CODE REVIEW

**Comment by kazupon** [comment]
Thank you for your contribution!

Your PR is good! 👍 
But, GitHub Actions `actions/checkout` fails to fetch your repo. 🤔 
Would you have anything about it?

**Comment by tmlmt** [comment]
ありがとう！
🤔 not that I know of. The repo is public and I haven't touched it since I made the pull request. Is there anything I should check?

**Comment by kazupon** [comment]
Thanks!
I've removed the `with` from workflow file at [this commit](https://github.com/intlify/routing/commit/1616a4b1264218920fc8db8f9be5de36825681b1)

I ran the github action on your PR again. But it still fails. Maybe your PR needs to sync my commits.
Could you give it a try? 🙏

**Comment by tmlmt** [comment]
Hey @kazupon, I've now synced my branch with yours. Not sure if it makes a difference though. 
Have made some pull requests recently to other repos the same way and we didn't face a similar issue ://

**Comment by kazupon** [comment]
Github actions just work now!
Thanks!

**Review by kazupon — APPROVED** [review]

**Comment by tmlmt** [comment]
Awesome. Do you think you can cascade this to @nuxtjs/i18n@next?

**Pull request merged**
